openapi: 3.0.3
info:
  title: Stacks API
  version: 1.0.0
  description: API para criar stacks no CloudFormation

# CORS (HTTP API)
x-amazon-apigateway-cors:
  allowOrigins: ["*"]
  allowHeaders: ["*"]
  allowMethods: ["*"]

paths:
  /stacks:
    post:
      summary: Inicia criação de uma Stack
      security:
        - CognitoAuthorizer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [accountName, stackName, template]
              properties:
                accountName: { type: string }
                stackName:   { type: string }
                template:    { type: object }
                templateUrl: { type: string, format: uri }
                parameters:  { type: object, additionalProperties: { type: string } }
      responses:
        '200':
          description: Criação iniciada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:   { type: string }
                  stackId:   { type: string }
                  status:    { type: string }

      # Integração HTTP API v2 (Lambda proxy)
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: aws_proxy
        httpMethod: POST
        uri: arn:aws:apigateway:{REGION}:lambda:path/2015-03-31/functions/arn:aws:lambda:{REGION}:{ACCOUNT_ID}:function:{LAMBDA_NAME}/invocations

components:
  securitySchemes:
    CognitoAuthorizer:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authorizer:
        type: jwt
        identitySource: "$request.header.Authorization"
        jwtConfiguration:
          issuer:   "https://cognito-idp.{REGION}.amazonaws.com/{USER_POOL_ID}"
          audience: ["{APP_CLIENT_ID}"]
